---
lxd__upstream_enabled: False
lxd__packages: [
  'qemu',
  'qemu-system-x86',
  'qemu-utils',
  'qemu-block-extra',
  'qemu-system',
  'lxd'
]
lxd__group_preseed:
  - name: 'storage-default'
    seed:
      storage_pools:
        - name: 'default'
          config:
            source: '/data/lxd'
          driver: 'btrfs'
